### ISSUE TITLE
win7 系统  ，发现加载siutf8.dll 时，SI会卡死

### ISSUE THREAD

**Issue by hiproz** [redxu/siutf8#1]
用的http://www.cnblogs.com/Red_angelX/p/3713935.html 的包 ，单独用和用新的loader效果是一样的，只要加载 siutf8.dll 就会出现

**Comment by redxu** [comment]
你可以用裸系统试一下,我怀疑是某些杀毒软件的行为导致的.SIUTF8里面勾了一些文件操作,有些杀毒软件(我遇到过公司的USB管控程序)也会很勾这些API,冲突了就会导致卡死
