### ISSUE TITLE
文件在外部被修改后，source insight检测不到改动。

### ISSUE THREAD

**Issue by fs000x** [redxu/siutf8#2]
文件在外部被修改后，source insight检测不到改动。把此文件关闭并打开后，内容还是修改之前的。必须把source insight关闭，再重新打开，文件内容才是修改之后的。

**Comment by redxu** [comment]
嗯,这是一个已知问题,目前是由于siutf8的实现方式决定的.因为针对utf8文件,实际上SI对该文件的所有操作都会转义到另外一个临时的gbk文件上面,所以依照SI的实现方式是检测不到外部文件变动的.
不过仔细想了一下,可以自己实现一个的文件对比过程,然后重新生成gbk,在利用SI的机制实现检测,我下周实验一下

**Comment by fs000x** [comment]
那ANSI编码的文件如果在装插件之前就已经在SI内打开了，关闭SI并安装插件后重新打开SI，该文件显示乱码，也是这个检测机制的问题吗？

**Comment by fs000x** [comment]
还有，出现过保存操作 保存不上的问题！

**Comment by redxu** [comment]
显示乱码的文件可否提供一下?理论上你说的情况不会,因为插件会判断文件编码.
但是一些中文的文件会被误判为utf8,因为utf8的检测不能做到很精细.
即时编码判断错误了,转换后因该还是原来的文件

**Comment by fs000x** [comment]
可以这样重现（应该是同一个问题导致）：
不用卸载插件。
在SI里新建一个文件，里面输入几个汉字，保存——>此文件会被保存为ANSI编码。在SI里关闭此文件（不要关闭SI，关闭再打开就不会出现乱码了）。
把此文件转为UTF-8或UTF-8无BOM编码（我用notepad++转的），保存。
用SI打开，出现的是乱码。

**Comment by redxu** [comment]
更新了一个版本,解决了UTF8外部更改的问题;
至于你说的另外一个问题,打开之后编码改变(gbk->u8),这种情况实际运用中不多,虽可以实现检测,但带价太大,目前插件的机制是文件只读一次编码,之后就认为编码不会改变,如果要每次都把文件重读一遍判断编码,没这个必要.因此不做修改.
