### ISSUE TITLE
Support UTF-8 non-BOM

### ISSUE THREAD

**Issue by zhaoxiaoguang** [redxu/siutf8#4]
你好，可以支持不带BOM的utf-8吗？

**Comment by qianfan-Zhao** [comment]
@zhaoxiaoguang  可以支持。不过现在source insight4.0已经发布了，本身就支持unicode编码。

**Comment by redxu** [comment]
utf-8带bom和不带bom的都支持
我去看看si 4.0更新了什么

**Comment by hgyxbll** [comment]
si 4.0更新的更多,标签和utf-8都有了.
但是不支持GBK了. 难道要再搞一个gbk插件?

以下是一些我总结的更新点.
Sourceinsight4.0对3.5的主要更新点在于:

1. 支持代码片段   
2. 代码可折叠
3. 旁边有代码缩略图
4. 支持主题
5. 带文件和目录比较功能
6.格式化代码
7. 导出成html
8.更强的文件备份
9.窗口有标签
10.支持Unicode
11.点击单词自动高亮相同单词
12. 配置保存格式为XML

以上加粗的是我认为非常重要的功能,本来3.5版本已经非常强悍,但配置是二进制格式,没有标签,不能识别UTF-8是我最大的痛点.

目前终于把痛点都解决了,4.0憋这么久果然还是有货的.

 

但是4.0目前仍旧没有解决输入法跟随, 最主要是目前版本居然不能使用QQ拼音输入法打字(微软的输入法倒是可以)

另外UTF-8是支持了, 但GBK却变成乱码不支持了.

推荐3.5和4.0一起使用, GBK就使用3.5, UTF-8就使用4.0.

PS: 代码应尽量使用UTF-8保存, UTF-8可兼容于IAR, VS, SI4, Linux, Sublime, Xcode等主流IDE或编辑器,可省去很多麻烦.

**Comment by hiberhe** [comment]
在xp中，中文无法向代码窗口输入。查找之类的输入框可以输入中文，不知道是不是控件属性的问题。可以通过粘贴向代码窗"输入"中文，而且删除时再也没有删除一半的问题。

转换为utf-8文件格式就可以正确显示。不过我在xp中仍然无法输入中文，不管是第三方输入法还是系统自带的智能ABC或微软拼音。而且si居然没有设置文件编码格式的选项。据说win10自带输入法可以输入中文。 

si4还远不够完美啊，不过更新了就是好事！

**Comment by redxu** [comment]
粗略试用了一下SI4,感觉是在像sublime text靠拢.
编码强制为unicode了(utf-8?),因此没插件的情况下不在支持GBK,这也可以理解.如果SI4和SI3的处理流程没多大变化的话,做个u2g的插件也不难,不过我希望类似st那样通过官方的接口来实现插件.
代码折叠这个方便太多了,缩略图功能也比st做的强大.算是个亮点.
对于中文支持,这帮开发人员还是和SI3一个鸟性,WIN7 x64下都无法输入中文... 同样的st是不存在中文输入问题的.
标签切换的速度感觉有点慢,不知道是不是心理作用.
最后说一说SI4的licence,我估计短时间内在国内普及比较难,SI4的licence加了网络校验.不再像SI3那样纯本地校验了.

**Comment by hiberhe** [comment]
文件格式用的utf-8，有无BOM均能识别。

代码折叠和高亮选中的相同标识符都很好用，不过下划线高亮选中的标识符的其余位置不太习惯，还是visual assist x中那种通过颜色标识记更好点。另外，查找框中输入框的下划线也好不习惯。

不过总体上si4还是很棒，希望后续能够改进中文支持（估计看有多少国内公司采购吧）。虽然slick edit之类也很棒，不过si胜在小巧、美观和快速。si4安装文件看起来很大，其实大部分是帮助文件。像si3才3M多的安装个头，这个就秒slickedit无数条街。

其实对于公司而言价格也不贵，$239换成人民币含增值税也才1900多点，批量还有折扣。希望多点国内公司买，好增强中文支持:)

不管怎么样，si还活着，就是好消息！

关于si4的license，其实远没看起来那么强大，主程序未加混淆，因而使用ollydbg或ida之类的工具，很方便就能简单粗暴的跳过验证的。

**Comment by redxu** [comment]
本地lic没有网络校验,流程我大概清楚了,pediy已经有人发补丁了.

**Comment by zhaoxiaoguang** [comment]
假设原有文件为utf-8带BOM格式，如果文件在外部被转换成了utf-8无BOM格式（比如用notepad++），这个时候插件识别就有问题了，除非关闭SourceSight，再次打开才能正确识别。 @redxu

**Comment by redxu** [comment]
@zhaoxiaoguang 
插件设计的如此.大部分场景下,一个文件的编码是不会改变的,只会改变文件的内容.
我认为加上这个功能性价比不高,会使插件的流程变得更乱,而仅仅是为了解决不常出现的问题.
因此对这种情况未做支持.

**Comment by zhaoxiaoguang** [comment]
@redxu OK，谢谢！
Source Insight 4.00.0082中在C文件中输入汉字“用”，会被自动转换成圆括号"()"，不知道为什么？最新版本已经没有这个毛病了
